/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package franciscopau.tp_copro1;

/**
 *
 * @author PC
 */
public class FranciscoPauTP_COPRO1 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        System.out.println("	                                                                                                    ..--==+++***###88XXXXXXXXXXXXXXXXXXXXXX88###***+++==--..                                                                                                     	");	
	System.out.println("	                                                                                          .--=++*#xXXXXXXXXXXXXXXXXX**********************######XXXXXXXXXXXXXXXx#*++=--.                                                                                         	");
	System.out.println("	                                                                                 .-=+*#xXXXXXXXXXx###*++===-----------------------------------------------==++**##xXXXXXXXXXx#*+=-.                                                                                	");
	System.out.println("	                                                                          .-=+#xXXXXXXXx##*+==------------------------------------------------------------------------=+**#xxXXXXXXXx#+=-.                                                                         	");
	System.out.println("	                                                                    .-+*xXXXXXXXx#*+=------------------------------------------------------------------------------------------=+*#xXXXXXXXx*e-.                                                                   	");
	System.out.println("	                                                               -+*#XXXXXXX#+=-------------------------------------------- +-------------+--------------------------------------------=*#xXXXXXXXx*=-                                                              	");
	System.out.println("	                                                          .+*#XXXXXXX#+=---------=**#*-----------------------------------=X#------------#X=----------------------------------*#**==--------=+*xXXXXXXXx*=.                                                         	");
	System.out.println("	                                                      .+*XXXXXXX#=+=-------=+*#8XXXXX=-----------------------------------+XX8**********8XX*-----------------------------------=XXXXX8#*+--------=+#xXXXXXXX*e.                                                     	");
	System.out.println("	                                                  .+*XXXXXXX#=+-------=+*8XXXXXXXXXX+------------------------------------XXXXXXXXXXXXXXXXXX------------------------------------+XXXXXXXXXX8#+=-------+#xXXXXXXX*=.                                                 	");
	System.out.println("	                                               .+*XXXXXXX#+=------=*#XXXXXXXXXXXXXXX=-----------------------------------=XXXXXXXXXXXXXXXXXX+-----------------------------------=XXXXXXXXXXXXXXX#*=-------+#XXXXXXXxe-                                              	");
	System.out.println("	                                            .+*XXXXXXX*=------=*#XXXXXXXXXXXXXXXXXXX+-----------------------------------=XXXXXXXXXXXXXXXXXX=-----------------------------------+XXXXXXXXXXXXXXXXXXX#*=------=#XXXXXXXXe.                                           	");
	System.out.println("	                                          -#XXXXXXX#=------+##XXXXXXXXXXXXXXXXXXXXXXX=---------------------------------+XXXXXXXXXXXXXXXXXXXX+----------------------------------XXXXXXXXXXXXXXXXXXXXXXXX#+------=#XXXXXXX#-                                        	");
	System.out.println("	                                       -xXXXXXXX8+------+#XXXXXXXXXXXXXXXXXXXXXXXXXXXX+--------------------------------XXXXXXXXXXXXXXXXXXXXXX-------------------------------+XXXXXXXXXXXXXXXXXXXXXXXXXXXX#+------+xXXXXXXX*-                                      	");
	System.out.println("	                                     -xXXXXXXX#=-----=#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#=-----------------------------+XXXXXXXXXXXXXXXXXXXXXX+-----------------------------=#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#=-----=#XXXXXXX#-                                    	");
	System.out.println("	                                   -xXXXXXXX#=-----+8XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX*=-------------------------+XXXXXXXXXXXXXXXXXXXXXXXX+-------------------------=*XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX*-----=#XXXXXXX#-                                  	");
	System.out.println("	                                  eXXXXXXX8=-----+8XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#*+=-------------------+XXXXXXXXXXXXXXXXXXXXXXXXXX+-------------------=+*#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX*-----=xXXXXXXX*                                 	");
	System.out.println("	                                -XXXXXXXX*-----+XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=####***###*8XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX88####****####=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+-----*XXXXXXXX#                               	");
	System.out.println("	                               -XXXXXXXX=-----#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#-----=XXXXXXXX+                              	");
	System.out.println("	                              +XXXXXXXX=----=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=-----XXXXXXXX+                             	");
	System.out.println("	                             +XXXXXXXX=----=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=----=XXXXXXXXe                            	");
	System.out.println("	                            .XXXXXXXX+-----XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-----+XXXXXXXXe                           	");
	System.out.println("	                            xXXXXXXXX-----*XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX*-----XXXXXXXXe                          	");
	System.out.println("	                            XXXXXXXX*-----XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-----*XXXXXXXX                           	");
	System.out.println("	                            XXXXXXXX+-----XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=----+XXXXXXXX                           	");
	System.out.println("	                            XXXXXXXX+-----XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-----+XXXXXXXX                           	");
	System.out.println("	                            xXXXXXXX#-----xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-----#XXXXXXXX                           	");
	System.out.println("	                            *XXXXXXXX=----=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx-----#XXXXXXX#                           	");
	System.out.println("	                             xXXXXXXXx-----*XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX8XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX8XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx-----#XXXXXXX#                            	");
	System.out.println("	                              XXXXXXXX#-----#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#*ee------ee*#XXXXXXXXXXXXXXXX8#####8XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX8#####8XXXXXXXXXXXXXXXX#ee------ee#xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx-----#XXXXXXXX#                             	");
	System.out.println("	                               #XXXXXXX#-----+XXXXXXXXXXXXXXXXXXXXXXXXXX#=---------------=*XXXXXXXXXX#+----------=*xXXXXXXXXXXXXXXXXXXXXXXXXXXXXx*=----------=*XXXXXXXXXX#+---------------=#XXXXXXXXXXXXXXXXXXXXXXXXXXx-----#XXXXXXXX#                             	");
	System.out.println("	                                #XXXXXXXX-----=xXXXXXXXXXXXXXXXXXXXXXXx=--------------------*XXXXXX+-----------------+xXXXXXXXXXXXXXXXXXXXXXXx+-----------------+XXXXXX*--------------------=xXXXXXXXXXXXXXXXXXXXXXXx=-----#XXXXXXX#                               	");
	System.out.println("	                                 xXXXXXXXX+-----+XXXXXXXXXXXXXXXXXXXXx------------------------#XX#---------------------=#XXXXXXXXXXXXXXXXXX#=---------------------#XX#------------------------#XXXXXXXXXXXXXXXXXXXXx-----#XXXXXXXX#                                	");
	System.out.println("	                                  .#XXXXXXXX=-----+XXXXXXXXXXXXXXXXXx--------------------------=*------------------------=#XXXXXXXXXXXXXX#=------------------------*=--------------------------xXXXXXXXXXXXXXXXXXx-----=#XXXXXXX#.                                 	");
	System.out.println("	                                    -#XXXXXXX#=-----+8XXXXXXXXXXXXXX=------------------------------------------------------+XXXXXXXXXXXX+------------------------------------------------------=XXXXXXXXXXXXXXXx-----=#XXXXXXX#-                                   	");
	System.out.println("	                                      -#XXXXXXXX+------*xXXXXXXXXXXX---------------------------------------------------------xXXXXXXXXx---------------------------------------------------------XXXXXXXXXXXXXx-----+#XXXXXXX#-                                     	");
	System.out.println("	                                        .eXXXXXXXX*=-----=*xXXXXXXXX----------------------------------------------------------#XXXXXX#----------------------------------------------------------XXXXXXXXXXx------*#XXXXXXX#.                                       	");
	System.out.println("	                                           -eXXXXXXXX*------=*#XXXXX-----------------------------------------------------------#XXXX#-----------------------------------------------------------XXXXXXXx-------+#XXXXXXX#-                                          	");
	System.out.println("	                                              -eXXXXXXXX*=-----=XXXx------------------------------------------------------------#XX#-------------------------------------------------------------XXxx=-------*#XXXXXXX#-                                             	");
	System.out.println("	                                                  -eXXXXXXXX#+----Xx+------------------------------------------------------------XX-------------------------------------------------------------+x-------+#xXXXXXXX#-                                                	");
	System.out.println("	                                                    .eXXXXXXXX#+-----------------------------------------------------------------++----------------------------------------------------------------+#xXXXXXXXX#.                                                   	");
	System.out.println("	                                                        .=*XXXXXXXX#*=------------------------------------------------------------------------------------------------------------------------=*#xXXXXXXXX#.                                                       	");
	System.out.println("	                                                             -e#XXXXXXXX#*+-------------------------------------------------------------------------------------------------------------=+*#xXXXXXXX#+-                                                            	");
	System.out.println("	                                                                 .-e*xXXXXXXXx#*+=------------------------------------------------------------------------------------------------=+*#xXXXXXXXx##e+-.                                                                	");
	System.out.println("	                                                                       .-e*#XXXXXXXXx#*+=----------------------------------------------------------------------------------=+*#xXXXXXXXX##e-.                                                                      	");
	System.out.println("	                                                                              --e*#xXXXXXXXXx##**+==------------------------------------------------------------==+**##xXXXXXXXXX##ee-                                                                             	");
	System.out.println("	                                                                                      .-=e*#xXXXXXXXXXXxx####**++====-------------------------=====++****##xxXXXXXXXXXXx##e=-.           	                                                                        ");
    }
    
}
